### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by bala2it4u** [bala2it4u/DMH#1]
# Development needed
- [x] Mapper
- [x] Mapp by code
- [x] APP.CONFIG/WEN.CONFIG
- [x] NEXT/USE DEFAULT/lAST RUN/SKIP & RUN/CANCEL
- [ ] LOGGING LOG4NET
- [ ] INPUT SCREEN
- [ ] OUTPUT PRINT IN SCREEN
- [ ] CONFIGURATION SELECTION show which config is used(startup project to get configuration)
- [ ] show which class is mapped
- [ ] error handling, show valid error message why failed
- [ ] Tools option add screen ro get input like (breakpoint, 
build every time, Mapp by Code NameSpace&class template Name changing option)

- [ ] LuckyHomeUp(string methodName, object[] input)
- [ ] LuckyHomeDown(string methodName, object[] input, object output)

## Documentation needed
- [ ] Mapper
- [ ] Mapp by code
- [ ] APP.CONFIG/WEN.CONFIG
- [ ] NEXT/USE DEFAULT/lAST RUN/SKIP & RUN/CANCEL

**Comment by bala2it4u** [comment]
"show which class is mapped" can write in debug log
"OUTPUT PRINT IN SCREEN" print in console & debug also.
"error handling, show valid error message why failed" need more testing.
